# Generated by Django 5.0.2 on 2024-03-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone_no',
            field=models.IntegerField(default=8794534975),
            preserve_default=False,
        ),
    ]
