# Generated by Django 5.0.2 on 2024-03-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_student_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(default='CSE', max_length=100),
            preserve_default=False,
        ),
    ]
