# Generated by Django 5.0.2 on 2024-03-02 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_student_department'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='BookID',
            new_name='book_id',
        ),
    ]
