# Generated by Django 5.0.2 on 2024-03-06 20:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_rename_bookid_book_book_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField()),
                ('issued_by', models.CharField(max_length=100)),
                ('issue_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('return_date_time', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField()),
                ('return_status', models.BooleanField(default=False)),
                ('late_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
